<a href="https://colab.research.google.com/github/Redcoder815/Deep_Learning_PyTorch/blob/main/14GPUs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

Computing Devices

In [2]:
def cpu():
    """Get the CPU device."""
    return torch.device('cpu')

def gpu(i=0):
    """Get a GPU device."""
    return torch.device(f'cuda:{i}')

cpu(), gpu(), gpu(1)

(device(type='cpu'),
 device(type='cuda', index=0),
 device(type='cuda', index=1))

In [3]:
def num_gpus():
    """Get the number of available GPUs."""
    return torch.cuda.device_count()

num_gpus()

1

In [4]:
def try_gpu(i=0):
    """Return gpu(i) if exists, otherwise return cpu()."""
    if num_gpus() >= i + 1:
        return gpu(i)
    return cpu()

def try_all_gpus():
    """Return all available GPUs, or [cpu(),] if no GPU exists."""
    return [gpu(i) for i in range(num_gpus())]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

Tensors and GPUs

In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

Storage on the GPU

In [6]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [7]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.0305, 0.4312, 0.1865],
        [0.8262, 0.6516, 0.3404]])

In [9]:
Z = X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [12]:
Z.cuda(0) is Z

True

Neural Networks and GPUs

In [13]:
net = nn.Sequential(nn.LazyLinear(1))
net = net.to(device=try_gpu())

In [14]:
net(X)

tensor([[0.3408],
        [0.3408]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [15]:
net[0].weight.data.device

device(type='cuda', index=0)